#!/bin/bash

set -euo pipefail

JOBS=$( getconf _NPROCESSORS_ONLN )
COMPILER_PATH="/usr/bin/g++-5"

pushd workspace

pushd drake
bazel run --compiler=gcc-5 //:install `pwd`/../../install
bazel build --compiler=gcc-5 //automotive:*
popd # drake

popd # workspace

mkdir -p build

pushd build

mkdir -p pybind11
pushd pybind11
CXX=$COMPILER_PATH cmake ../../workspace/pybind11 -DCMAKE_INSTALL_PREFIX=../../install -DPYBIND11_TEST=False
make -j$JOBS VERBOSE=1 install
popd # pybind11

for dep in ign_cmake ign_tools ign_common ign_msgs ign_transport ign_rendering ign_gui ; do
    mkdir -p $dep
    pushd $dep
    CXX=$COMPILER_PATH cmake ../../workspace/$dep -DCMAKE_INSTALL_PREFIX=../../install
    make -j$JOBS VERBOSE=1 install
    popd
done

mkdir -p delphyne
pushd delphyne
CXX=$COMPILER_PATH cmake ../.. -DCMAKE_INSTALL_PREFIX=../../install
make -j$JOBS VERBOSE=1 install
popd

mkdir -p delphyne_gui
pushd delphyne_gui
CXX=$COMPILER_PATH cmake ../../workspace/delphyne_gui -DCMAKE_INSTALL_PREFIX=../../install
make -j$JOBS VERBOSE=1 install
popd

popd # build
