#!/bin/bash

# Copyright (c) 2017, Massachusetts Institute of Technology.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the Massachusetts Institute of Technology nor the names
#   of its contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE MASSACHUSETTS INSTITUTE OF TECHNOLOGY AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE MASSACHUSETTS
# INSTITUTE OF TECHNOLOGY OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -eu

# Here we install all of the dependencies necessary to build delphyne.  This
# includes the direct dependencies (as called out in
# https://github.com/ToyotaResearchInstitute/delphyne-gui/blob/master/README.md),
# as well as the indirect dependencies that we have from drake.  Note that we
# disable the '-o pipefail' directive above because we need to pipe 'yes'
# into the drake 'install_prereqs.sh' script for it to succeed.  Given that we
# have no other pipes in this file, this should be safe enough.

export DEBIAN_FRONTEND='noninteractive'

# Install the direct delphyne dependencies.
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends $(tr '\n' ' ' <<EOF
awscli
cmake
coreutils
curl
gcovr
git
lcov
libavdevice-dev
libboost-filesystem-dev
libfreeimage-dev
libglew-dev
libgts-dev
libicu-dev
libogre-1.9-dev
libprotobuf-dev
libprotoc-dev
libqt5multimedia5
libqwt-dev
libtinyxml2-dev
libzmq3-dev
mercurial
mesa-utils
pkg-config
protobuf-compiler
python
python3-vcstool
qtbase5-dev
ruby-ronn
uuid-dev
EOF
)

# Install the drake dependencies.
yes | sudo ./workspace/drake/setup/ubuntu/16.04/install_prereqs.sh
