#!/bin/bash

set -euo pipefail

JOBS=$( getconf _NPROCESSORS_ONLN )
COMPILER_PATH="/usr/bin/g++-5"

mkdir -p install

# The date that conforms part of the build URL is automatically parsed from the 
# drake respository's last commit date, avoiding us from doing it by hand.
pushd workspace/drake
COMMIT_DATE="$(git log -n 1 --pretty='format:%cd' --date=format:'%Y%m%d')"
popd
BUILD_URL="https://drake-packages.csail.mit.edu/drake/nightly/drake-$COMMIT_DATE-xenial.tar.gz"

# Downloads drake binary and untars it into the install directory.
wget -qO- $BUILD_URL | tar xvz -C `pwd`/install --strip 1

mkdir -p build

pushd build

for dep in ign_cmake ign_tools ign_common ign_msgs ign_transport ign_rendering ign_gui ; do
    mkdir -p $dep
    pushd $dep
    CXX=$COMPILER_PATH cmake ../../workspace/$dep -DCMAKE_CXX_STANDARD=11 -DCMAKE_INSTALL_PREFIX=../../install
    make -j$JOBS VERBOSE=1 install
    popd
done

mkdir -p delphyne
pushd delphyne
CXX=$COMPILER_PATH cmake ../.. -DCMAKE_INSTALL_PREFIX=../../install
make -j$JOBS VERBOSE=1 install
popd

mkdir -p delphyne_gui
pushd delphyne_gui
CXX=$COMPILER_PATH cmake ../../workspace/delphyne_gui -DCMAKE_INSTALL_PREFIX=../../install
make -j$JOBS VERBOSE=1 install
popd

popd # build
