#!/bin/bash

set -eu

# Here we install all of the dependencies necessary to build delphyne.  This
# includes the direct dependencies (as called out in
# https://github.com/ToyotaResearchInstitute/delphyne-gui/blob/master/README.md),
# as well as the indirect dependencies that we have from drake.  Note that we
# disable the '-o pipefail' directive above because we need to pipe 'yes'
# into the drake 'install_prereqs.sh' script for it to succeed.  Given that we
# have no other pipes in this file, this should be safe enough.

export DEBIAN_FRONTEND='noninteractive'

yes | sudo /opt/drake/share/drake/setup/install_prereqs
for script in find ./src -name 'install_prereqs.sh'; do
    yes | sudo $script
done
