#!/bin/bash

set -euo pipefail

# The setup_early script installs just the necessary bootstrap dependencies to
# be able to build the workspace.  All other dependencies will be installed
# during setup_late.

export DEBIAN_FRONTEND='noninteractive'

# Install the direct delphyne dependencies.
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list'
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends $(tr '\n' ' ' <<EOF
awscli
curl
git
libignition-cmake-dev
mercurial
pkg-config
pylint
python-pip
python3-vcstool
EOF
)
# Install pip dependencies
# TODO(apojomovsky) #446 Replace this by a deb install as soon as we go to 18.04
pip install --user pycodestyle
