#!/bin/bash

set -eo pipefail

die() {
    echo "$*" 1>&2
    exit 1
}

source install/setup.bash

colcon test --event-handlers=console_direct+ \
       --return-code-on-test-failure \
       --packages-select delphyne delphyne-gui
